/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static java.lang.Integer.valueOf;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author oyh
 */
public class Consumer_main extends javax.swing.JFrame {
    String path=System.getProperty("user.dir");
    private File_controller ff=new File_controller();
    public static Thread t;
    /**
     * Creates new form Consumer
     */
    public Consumer_main(String i) {
        initComponents(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String i) {
        provider p=new provider();

        jPanel1 = new JPanel();
        jPanel2 = new Consumer_check_budget(i);
        jTextField1 = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();

        setTitle("Consumer");
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(800, 600);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        setContentPane(jPanel1);
        jPanel1.setLayout(null);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(200,200,300,100);

        if(ff.get_hours()==1){
            jTextField1.setText("Good evening, Dear "+ff.get_Name(i)+" !");
        }else if(ff.get_hours()==2){
            jTextField1.setText("Good Morning, Dear "+ff.get_Name(i)+" !");
        }else if(ff.get_hours()==3){
            jTextField1.setText("Good Afternoon, Dear "+ff.get_Name(i)+" !");
        }

        jTextField1.setBorder(null);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextField1.setEditable(false);

        jTextField1.setBounds(200, 50, 500, 100);
        jPanel1.add(jTextField1);

        jButton2.setText("View");
        jButton2.setBounds(100, 400, 100, 50);

        jButton3.setText("Budget");
        jButton3.setBounds(250, 400, 100, 50);

        jButton4.setText("Tariff");
        jButton4.setBounds(400, 400, 100, 50);

        jButton5.setText("Bills");
        jButton5.setBounds(550, 400, 100, 50);

        jButton1.setText("Back");
        jButton1.setBounds(650, 500, 80, 50);

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JDialog f1 = new Consumer(new JFrame(),true);
                f1.setVisible(true);
            }
        });

        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1 = new Consumer_View(i);
                f1.setVisible(true);
            }
        });

        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
               JFrame f1 = new Consumer_Budget(i);
               f1.setVisible(true);
            }
        });

        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    setVisible(false);
                    JFrame f1 = new Consumer_Tariff(i);
                    f1.setVisible(true);
                }catch (IOException r){
                    System.out.println("View tariff error!");
                }
            }
        });

        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1 = new Consumer_Bills(i);
                f1.setVisible(true);
            }
        });

        jPanel1.add(jButton1);
        jPanel1.add(jButton2);
        jPanel1.add(jButton3);
        jPanel1.add(jButton4);
        jPanel1.add(jButton5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));


    }// </editor-fold>

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify

    private javax.swing.JPanel jPanel1;
    private JTextField jTextField1;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JPanel jPanel2;

    // End of variables declaration
}
