/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author oyh
 */

public class Consumer_Bills extends JFrame {

    /**
     * Creates new form NewJPanel7
     */
    public Consumer_Bills(String i) {
        initComponents(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String i) {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        String path=System.getProperty("user.dir");
        setSize(800,600);
        jPanel1=new JPanel();
        setContentPane(jPanel1);
        setResizable(false);
        setLayout(null);

        textField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 =new JButton();

        jPanel1.setBackground(new Color(255,255,255));
        setBackground(new java.awt.Color(255, 255, 255));

        Date today=new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM");
        String D=ft.format(today);
        String[] a=new String[4];
        File f=new File(path+"/bills/"+i+"_"+D+".txt");
        try{
            BufferedReader br1=new BufferedReader(new FileReader(f));
            a=br1.readLine().trim().split(",");

        } catch (IOException r){

        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {a},
                new String [] {
                        "Ele", "Ele Cost", "Gas", "Gas cost"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1=new Consumer_main(i);
                f1.setVisible(true);
            }
        });

        jPanel1.add(textField1);
        jPanel1.add(jScrollPane1);
        jPanel1.add(jButton1);

        String s="This is current month bill";
        textField1.setText(s);
        textField1.setBorder(null);
        textField1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        textField1.setEditable(false);
        textField1.setSelectionStart(s.length());

        textField1.setBounds(120,50,500,40);
        jScrollPane1.setBounds(120,120,500,400);
        jButton1.setBounds(650,500,100,40);


    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textField1;
    private JPanel jPanel1;
    private JButton jButton1;
    // End of variables declaration
}
