
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author oyh
 */
public class Consumer extends JDialog {
    provider_controller p=new provider_controller();
    private File_controller ff=new File_controller();
    String path=System.getProperty("user.dir");
    /**
     * Creates new form Consume
     */
    public Consumer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setResizable(false);
        setSize(800,600);
        jPanel1 =new JPanel();
        setContentPane(jPanel1);
        jPanel1.setBackground(new Color(255,255,255));
        jPanel1.setLayout(null);
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jTextField4 = new JTextField();
        jTextField5 = new javax.swing.JPasswordField();

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setText("Please input the Account Number and Password!");
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setBounds(100,50,500,60);

        jTextField2.setText("Account:");
        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.setBounds(100,400,70,30);

        jTextField3.setBounds(200,400,100,30);

        jTextField4.setText("Password:");
        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.setBounds(350,400,100,30);

        jTextField5.setBounds(470,400,100,30);

        jPanel1.add(jTextField1);
        jPanel1.add(jTextField2);
        jPanel1.add(jTextField3);
        jPanel1.add(jTextField4);
        jPanel1.add(jTextField5);
        jPanel1.add(jButton1);
        jPanel1.add(jButton2);
        jButton1.setBounds(600,450,70,30);
        jButton2.setBounds(600,500,70,30);

        jButton1.setText("Enter");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<String> ss=ff.getData_User();
                String s1=jTextField3.getText();
                String s2=jTextField5.getText();

                if(ss.contains(s1)&&s2.equals("111111")){
                    setVisible(false);
                    JFrame f1=new Consumer_main(s1);
                    f1.setVisible(true);
                }else if(s2.equals("")){
                    JOptionPane.showMessageDialog(null, "Password is null, Please input again!", "alert", JOptionPane.ERROR_MESSAGE);
                }else if(s1.equals("")){
                    JOptionPane.showMessageDialog(null, "Account is null, Please input again!", "alert", JOptionPane.ERROR_MESSAGE);
                }else if(s1.equals("")&&s2.equals("")){
                    JOptionPane.showMessageDialog(null, "Input is null, Please input again!", "alert", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Account Number or Password Error!", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1=new Welcome();
                f1.setVisible(true);
            }
        });



    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consumer dialog = new Consumer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JPasswordField jTextField5;

    private JPanel jPanel1;

    // End of variables declaration
}
