/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Pattern;

/**
 *
 * @author oyh
 */
public class Consumer_Budget extends JFrame {
    household h1=new household();
    /**
     * Creates new form NewJPanel5
     */
    public Consumer_Budget(String i) {
        initComponents(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String i) {
        jPanel1=new JPanel();
        setContentPane(jPanel1);

        setSize(800,600);
        jPanel1.setLayout(null);
        jTextField1 = new javax.swing.JTextField(5);
        jTextField2 = new javax.swing.JTextField(5);
        jTextField3 = new javax.swing.JTextField(5);
        jTextField4 = new javax.swing.JTextField(5);
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField(5);
        jTextField7 = new javax.swing.JTextField(5);
        jTextField8 = new javax.swing.JTextField(5);
        jTextField9 = new javax.swing.JTextField(5);

        jButton1 = new JButton();
        jButton2 = new JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("Eletric");
        jTextField1.setEditable(false);
        jTextField1.setBorder(null);

        jTextField2.setText("Ele cost");
        jTextField2.setEditable(false);
        jTextField2.setBorder(null);

        jTextField3.setText("Gas");
        jTextField3.setEditable(false);
        jTextField3.setBorder(null);

        jTextField4.setText("Gas cost");
        jTextField4.setEditable(false);
        jTextField4.setBorder(null);

        jTextField5.setText("Please input your budget!");
        jTextField5.setEditable(false);
        jTextField5.setBorder(null);
        jTextField5.setFont(new java.awt.Font("Lucida Grande", 0, 20));

        add(jTextField1);
        add(jTextField2);
        add(jTextField3);
        add(jTextField4);
        add(jTextField5);
        add(jTextField6);
        add(jTextField7);
        add(jTextField8);
        add(jTextField9);
        add(jButton1);
        add(jButton2);

        jTextField5.setBounds(100,30,500,40);
        jTextField1.setBounds(100,100,100,40);
        jTextField2.setBounds(100,200,100,40);
        jTextField3.setBounds(100,300,100,40);
        jTextField4.setBounds(100,400,100,40);

        jTextField6.setBounds(300,100,100,40);
        jTextField7.setBounds(300,200,100,40);
        jTextField8.setBounds(300,300,100,40);
        jTextField9.setBounds(300,400,100,40);

        String[] s=h1.get_budget(i);

        jTextField6.setText(s[0]);

        jTextField7.setText(s[1]);

        jTextField8.setText(s[2]);

        jTextField9.setText(s[3]);

        jButton1.setText("Save");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String[] ss=new String[4];
                String a1=jTextField6.getText();
                String a2=jTextField7.getText();
                String a3=jTextField8.getText();
                String a4=jTextField9.getText();
                ss[0]=a1;ss[1]=a2;ss[2]=a3;ss[3]=a4;
                String pattern = "([1-9]\\d*\\.?\\d*)|(0\\.\\d*[1-9])";

                boolean isMatch1 = Pattern.matches(pattern, a1);
                boolean isMatch2 = Pattern.matches(pattern,a2);
                boolean isMatch3 = Pattern.matches(pattern, a3);
                boolean isMatch4 = Pattern.matches(pattern,a4);
                if(isMatch1&&isMatch2&&isMatch3&&isMatch4){
                    h1.set_budget(i,ss);
                    JOptionPane.showMessageDialog(null, "Budget have been saved!", null, JOptionPane.INFORMATION_MESSAGE);
                }else if(a1.equals("")||a2.equals("")||a3.equals("")||a4.equals("")){
                    JOptionPane.showMessageDialog(null, "The input is null!", null, JOptionPane.INFORMATION_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Please input the right tariff", "alert", JOptionPane.ERROR_MESSAGE);
                }
                //h1.set_budget(i,ss);
                //JOptionPane.showMessageDialog(null, "Budget have been saved!", null, JOptionPane.INFORMATION_MESSAGE);
                jPanel1.updateUI();
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1=new Consumer_main(i);
                f1.setVisible(true);
            }
        });

        jButton1.setBounds(500,100,100,40);
        jButton2.setBounds(500,400,100,40);

    }// </editor-fold>

    // Variables declaration - do not modify
    private JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration
}
