/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.io.File;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author oyh
 */
public class Consumer_View_Today extends javax.swing.JPanel implements Runnable {
    String path=System.getProperty("user.dir");
    private File_controller ff=new File_controller();
    /**
     * Creates new form NewJPanel2
     */
    public Consumer_View_Today(String i) {
        setSize(600,600);
        setLayout(null);
        setBackground(new Color(255,255,255));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 =new JTextField();

        String[] c=new String[]{"Ele","Ele cost","Gas","Gas cost"};
        int[] columnWidth=new int[]{50,50,50,50};
        jTable1.setModel(getTableModel(i));
        TableColumnModel columnModel = jTable1.getColumnModel();// 获取列模型
        int count = columnModel.getColumnCount();// 获取列数量

        for (int a = 0; a < count; a++) {// 遍历列
            TableColumn column = columnModel.getColumn(a);// 获取列对象
            column.setHeaderValue(c[a]);
            column.setPreferredWidth(columnWidth[a]);// 以数组元素设置列的宽度
        }

        Date today=new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        String D=ft.format(today);

        jTextField1.setText("Today is "+D);
        jTextField1.setEditable(false);
        jTextField1.setBorder(null);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setBounds(80,20,500,35);
        jTable1.setBackground(new Color(255,255,255));
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBackground(new Color(255,255,255));
        jScrollPane1.setBounds(80,60,500,400);

        add(jScrollPane1);
        add(jTextField1);
//        initComponents(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String i) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));


//        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
//        jLabel1.setText("jLabel1");
        jTable1.setModel(getTableModel(i));
        jScrollPane1.setViewportView(jTable1);

        String[] c=new String[]{"Ele","Ele cost","Gas","Gas cost"};
        int[] columnWidth=new int[]{50,90,50,90};

        TableColumnModel columnModel = jTable1.getColumnModel();// 获取列模型
        int count = columnModel.getColumnCount();// 获取列数量
        for (int a = 0; a < count; a++) {// 遍历列
            TableColumn column = columnModel.getColumn(a);// 获取列对象
            column.setHeaderValue(c[a]);
            column.setPreferredWidth(columnWidth[a]);// 以数组元素设置列的宽度
        }
        jTable1.setPreferredScrollableViewportSize(new Dimension(280,400));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel1)))
                                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>

    public AbstractTableModel getTableModel(String i) {
        return new AbstractTableModel() {
            public int getColumnCount() {
                return 4;
            }
            public int getRowCount() {
                return ff.getData(i,"today").size();
            }
            public Object getValueAt(int row, int col) {
                switch (col) {
                    case (0): {
                        return ff.getData(i,"today").get(row).split(",")[4];
                    }
                    case (1): {
                        return ff.getData(i,"today").get(row).split(",")[5];
                    }
                    case (2): {
                        return ff.getData(i,"today").get(row).split(",")[6];
                    }
                    case (3):{
                        return ff.getData(i,"today").get(row).split(",")[7].trim();
                    }
                    default:
                        return "false";
                }
            }

        };
    }

    public void run() {
        while (true) {
            //每隔15秒钟更新JTable
            jTable1.validate();
            jTable1.updateUI();
            try {
                Thread.sleep(15000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private JTextField jTextField1;
    // End of variables declaration
}
