/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author oyh
 */
public class Manager_View_Today extends JPanel implements Runnable{
    String path=System.getProperty("user.dir");
    File_controller ff=new File_controller();
    /**
     * Creates new form Manager_View_today
     */
    public Manager_View_Today() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setSize(600,600);
        setLayout(null);
        setBackground(new Color(255,255,255));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 =new JTextField();

        String[] c=new String[]{"User","Ele","Ele cost","Gas","Gas cost"};
        int[] columnWidth=new int[]{50,50,50,50,50};
        jTable1.setModel(getTableModel_today());
        TableColumnModel columnModel = jTable1.getColumnModel();// 获取列模型
        int count = columnModel.getColumnCount();// 获取列数量

        for (int i = 0; i < count; i++) {// 遍历列
            TableColumn column = columnModel.getColumn(i);// 获取列对象
            column.setHeaderValue(c[i]);
            column.setPreferredWidth(columnWidth[i]);// 以数组元素设置列的宽度
        }

        Date today=new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        String D=ft.format(today);

        jTextField1.setText("Today is "+D);
        jTextField1.setEditable(false);
        jTextField1.setBorder(null);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setBounds(80,20,500,35);
        jTable1.setBackground(new Color(255,255,255));
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBackground(new Color(255,255,255));
        jScrollPane1.setBounds(80,60,500,400);

        add(jScrollPane1);
        add(jTextField1);


    }// </editor-fold>

    public AbstractTableModel getTableModel_today() {
        return new AbstractTableModel() {
            public int getColumnCount() {
                return 5;
            }
            public int getRowCount() {
                return ff.getData("today").size();
            }
            public Object getValueAt(int row, int col) {
                switch (col) {
                    case (0): {
                        return ff.getData("today").get(row).split(",")[2];
                    }
                    case (1): {
                        return ff.getData("today").get(row).split(",")[4];
                    }
                    case (2):{
                        return ff.getData("today").get(row).split(",")[5];
                    }
                    case (3):{
                        return ff.getData("today").get(row).split(",")[6];
                    }
                    case (4):{
                        return ff.getData("today").get(row).split(",")[7];
                    }
                    default:
                        return "false";
                }
            }

        };
    }

    public void run() {
        while (true) {
            //每隔15秒钟更新JTable
            jTable1.validate();
            jTable1.updateUI();
            try {
                Thread.sleep(15000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
    // Variables declaration - do not modify
    private JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private JTextField jTextField1;
    private JComboBox<String> jComboBox1;
    // End of variables declaration                   
}
