/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.regex.Pattern;

/**
 *
 * @author oyh
 */
public class Manager_Tariff extends JFrame {
    String path=System.getProperty("user.dir");
    private provider_controller p;
    /**
     * Creates new form NewJPanel3
     */
    public Manager_Tariff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        p=new provider_controller();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        File f=new File(path+"/tariff.txt");
        try {
            BufferedReader br1=new BufferedReader(new FileReader(f));
            String s=br1.readLine().trim();
            String[] a=s.split(",");
            br1.close();
            jPanel1 =new JPanel();
            jTextField1 = new javax.swing.JTextField(10);
            jTextField2 = new javax.swing.JTextField(10);
            jTextField3 = new javax.swing.JTextField(10);
            jTextField4 = new javax.swing.JTextField(10);
            jTextField5 = new JTextField();
            jButton1 = new javax.swing.JButton();
            jButton2 = new JButton();

            setSize(800,600);
            setContentPane(jPanel1);

            setBackground(new java.awt.Color(255, 255, 255));
            setLayout(null);
            jPanel1.setLayout(null);
            jPanel1.setBackground(new Color(255,255,255));
            jTextField1.setText("Eletric Tariff");
            jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
            jTextField1.setEditable(false);
            jTextField1.setBorder(null);

            jTextField2.setText("Gas Tariff");
            jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
            jTextField2.setEditable(false);
            jTextField2.setBorder(null);

            jTextField5.setText("Please input the Tariff");
            jTextField5.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
            jTextField5.setEditable(false);
            jTextField5.setBorder(null);

            jTextField3.setText(a[0]);

            jTextField4.setText(a[1]);

            jPanel1.add(jTextField1);
            jPanel1.add(jTextField2);
            jPanel1.add(jTextField3);
            jPanel1.add(jTextField4);
            jPanel1.add(jTextField5);
            jPanel1.add(jButton1);
            jPanel1.add(jButton2);

            jTextField1.setBounds(130,100,120,30);
            jTextField2.setBounds(130,300,120,30);
            jTextField3.setBounds(430,100,100,30);
            jTextField4.setBounds(430,300,100,30);
            jTextField5.setBounds(130,30,300,40);
            jButton1.setBounds(550,400,100,30);
            jButton2.setBounds(550,500,100,30);

            jButton1.setText("Save");
            jButton1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        String s1=jTextField3.getText();
                        String s2=jTextField4.getText();
                        String pattern = "([1-9]\\d*\\.?\\d*)|(0\\.\\d*[1-9])";

                        boolean isMatch1 = Pattern.matches(pattern, s1);
                        boolean isMatch2 = Pattern.matches(pattern,s2);
                        if(isMatch1&&isMatch2){
                            p.set_tariff(Double.parseDouble(s1), Double.parseDouble(s2));
                            JOptionPane.showMessageDialog(null, "The tariff have been changed", null, JOptionPane.INFORMATION_MESSAGE);
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Please input the right tariff", "alert", JOptionPane.ERROR_MESSAGE);
                        }
                    }catch (IOException e2){
                        System.out.print("Setting tariff error!");

                    }
                }
            });

            jButton2.setText("Back");
            jButton2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setVisible(false);
                    JFrame f1=new Manager();
                    f1.setVisible(true);
                }
            });
        }catch(IOException e){

        }
    }// </editor-fold>

    private void check_input(){

    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private JTextField jTextField5;
    private JButton jButton2;
    private JPanel jPanel1;
    // End of variables declaration
}
