/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author oyh
 */
public class Manager_Bills extends JFrame {
    private provider_controller p;
    private File_controller ff=new File_controller();
    private Bills m;
    /**
     * Creates new form NewJPanel6
     */
    public Manager_Bills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        p=new provider_controller();
        m=new Bills();
        setLayout(null);

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jPanel1 =new JPanel();
        setBounds(0,0,800,600);
        setBackground(new java.awt.Color(255, 255, 255));

        List<String> ss=ff.getData_User();
        String[] s=new String[ss.size()];
        for (int a=0;a<ss.size();a++){
            s[a]=ss.get(a);
        }

        this.setContentPane(jPanel1);
        jPanel1.setBackground(new Color(255,255,255));
        jPanel1.setLayout(null);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(s));

        jTextField1.setText("Please select the account number!");
        jTextField1.setBorder(null);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextField1.setEditable(false);

        jButton1.setText("Send");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String i=(String)jComboBox1.getSelectedItem();
                m.email(i);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                JFrame f1=new Manager();
                f1.setVisible(true);
            }
        });

        jPanel1.add(jComboBox1);
        jPanel1.add(jTextField1);
        jPanel1.add(jButton1);
        jPanel1.add(jButton2);

        jTextField1.setBounds(150,100,500,50);
        jComboBox1.setBounds(150,400,100,40);
        jButton1.setBounds(600,400,100,40);
        jButton2.setBounds(600,500,100,40);

    }// </editor-fold>

    // Variables declaration - do not modify
    private JButton jButton1;
    private JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField1;
    private JPanel jPanel1;
    // End of variables declaration
}
