/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author oyh
 */
public class Manager_View_Mouth extends javax.swing.JPanel {
    String path=System.getProperty("user.dir");
    private provider_controller p=new provider_controller();
    private File_controller ff=new File_controller();
    /**
     * Creates new form Manager_View_today
     */
    public Manager_View_Mouth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setSize(600,600);
        setLayout(null);
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        textField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        List<String> ss=ff.getData_User();
        String[] s=new String[ss.size()];
        for (int i=0;i<ss.size();i++){
            s[i]=ss.get(i);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(s));
        jComboBox1.setSelectedIndex(0);

        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String item=(String)jComboBox1.getSelectedItem();
                jComboBox1.setSelectedItem(item);
                jTable2.setModel(getTableModel_mouth(item));

                String[] c=new String[]{"Date","Ele","Ele cost","Gas","Gas cost"};
                int[] columnWidth=new int[]{100,50,50,50,50};

                TableColumnModel columnModel = jTable2.getColumnModel();// 获取列模型
                int count = columnModel.getColumnCount();// 获取列数量
                for (int i = 0; i < count; i++) {// 遍历列
                    TableColumn column = columnModel.getColumn(i);// 获取列对象
                    column.setHeaderValue(c[i]);
                    column.setPreferredWidth(columnWidth[i]);// 以数组元素设置列的宽度
                }
            }
        });
        jScrollPane2.setViewportView(jTable2);

        textField1.setText("Please select the Account number!");
        textField1.setEditable(false);
        textField1.setBorder(null);
        textField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textField1.setBorder(null);
        textField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textField1.setBounds(30,20,300,35);
        jComboBox1.setBounds(350,20,70,35);
        jScrollPane2.setBounds(80,60,500,400);
        add(textField1);
        add(jScrollPane2);
        add(jComboBox1);


    }// </editor-fold>


    public AbstractTableModel getTableModel_mouth(String i) {
        return new AbstractTableModel() {
            public int getColumnCount() {
                return 5;
            }
            public int getRowCount() {
                return ff.getData(i,"mouth").size();
            }
            public Object getValueAt(int row, int col) {
                switch (col) {
                    case (0): {
                        String a=ff.getData(i,"mouth").get(row).split(",")[0];
                        return a;
                    }
                    case (1): {
                        String a=ff.getData(i,"mouth").get(row).split(",")[4];
                        return a;
                    }
                    case (2):{
                        String a=ff.getData(i,"mouth").get(row).split(",")[5];
                        return a;
                    }
                    case (3):{
                        String a=ff.getData(i,"mouth").get(row).split(",")[6];
                        return a;
                    }
                    case (4):{
                        String a=ff.getData(i,"mouth").get(row).split(",")[7].trim();
                        return a;
                    }
                    default:
                        return "false";
                }
            }

        };
    }


    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField textField1;
    // End of variables declaration
}
